# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_inspectre', '0003_auto_20170218_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
