# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_inspectre', '0004_auto_20170218_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=30)),
                ('latlng', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
